List scheduleItems = [
  //competition, general , talk, conference, workshop
  {
    "id": 0,
    "date": "DAY 1",
    "events": [
      {
        "eventName": "Tech Guest Lectures(Zil Money)",
        "eventCategory": "talk",
        "eventTime": "9:30 AM - 10:30 AM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "UNMASKED",
        "eventCategory": "talk",
        "eventTime": "11:00 AM - 1:00 PM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "Tech Guest Lectures(Riafy Technologies)",
        "eventCategory": "talk",
        "eventTime": "1:30 PM - 3:30 PM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "Med Expo",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "311, 312, 314",
      },
      {
        "eventName": "AUTOVAULT",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "315",
      },
      {
        "eventName": "Codeum Reparo Prelims",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 12:30 PM",
        "venue": "Computer Lab 1 - 313",
      },
      {
        "eventName": "Codeum Reparo",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 4:30 PM",
        "venue": "Computer Lab 1 - 313",
      },
      {
        "eventName": "Game Zone",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "310",
      },
      {
        "eventName": "Reverse Coding Prelims",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 11:30 AM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "Reverse Coding",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 4:30PM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "Lifeline Prelims",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 10:30 AM",
        "venue": "401",
      },
      {
        "eventName": "Lifeline (Intermediate Round)",
        "eventCategory": "competition",
        "eventTime": "11:00 AM - 12:30 PM",
        "venue": "403",
      },
      {
        "eventName": "Lifeline (F)",
        "eventCategory": "competition",
        "eventTime": "2:00 PM - 3:00 PM",
        "venue": "401",
      },
      {
        "eventName": "3D Printing Workshop",
        "eventCategory": "workshop",
        "eventTime": "1:30 PM - 4:30 PM",
        "venue": "Media Hall - 413",
      },
      {
        "eventName": "Defuse(P)",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 10:30 AM",
        "venue": "409,410",
      },
      {
        "eventName": "Defuse(R1)",
        "eventCategory": "competition",
        "eventTime": "10:30 AM - 11:30 AM",
        "venue": "410",
      },
      {
        "eventName": "Defuse(R2)",
        "eventCategory": "competition",
        "eventTime": "11:30 AM - 1:30 PM",
        "venue": " Microprocessor Lab - 404",
      },
      {
        "eventName": "Defuse(R3)",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 3:30 PM",
        "venue": " Microprocessor Lab - 404",
      },
      {
        "eventName": "Robotics Workshop",
        "eventCategory": "workshop",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "SDPK - 504",
      },
      {
        "eventName": "Paintball",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "External Auditorium",
      },
      {
        "eventName": "Fun Zone",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Elga/ Casa",
      },
      {
        "eventName": "SplashDown",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "External Auditorium",
      },
      {
        "eventName": "Open Mic",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Elga",
      },
      {
        "eventName": "News Desk",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "CCF",
      },
      {
        "eventName": "Treasure Hunt",
        "eventCategory": "competition",
        "eventTime": "10:00 AM - 11:30 AM",
        "venue": "New Block - B302, B303, B304",
      },
      {
        "eventName": "Breakout Prelims",
        "eventCategory": "competition",
        "eventTime": "1:00 PM - 2:00 PM",
        "venue": "New Block - B302, B303, B304",
      },
      {
        "eventName": "Drone Workshop",
        "eventCategory": "workshop",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "New Block - B307",
      },
      {
        "eventName": "Autoshow",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "College Ground",
      },
      {
        "eventName": "Battle Of Bands",
        "eventCategory": "competition",
        "eventTime": "5:30 PM - 7:30 PM",
        "venue": "Amphi Theatre",
      },
    ],
  },
  {
    "id": 1,
    "date": "DAY 2",
    "events": [
      {
        "eventName": ".ISSUE!",
        "eventCategory": "talk",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "Fun Zone",
        "eventCategory": "general",
        "eventTime": "9:30 PM - 5:30 PM",
        "venue": "Amphi",
      },
      {
        "eventName": "RoboSoccer",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Amphi",
      },
      {
        "eventName": 'Just "50"',
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "315",
      },
      {
        "eventName": "Med Expo",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "311, 312, 314",
      },
      {
        "eventName": "Binary Baton",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 11:30 PM",
        "venue": "Computer Lab 1 - 313",
      },
      {
        "eventName": "Binary Baton (Finals)",
        "eventCategory": "competition",
        "eventTime": "1:30 AM - 4:30 PM",
        "venue": "Computer Lab 1 - 313",
      },
      {
        "eventName": "Game Zone",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "310",
      },
      {
        "eventName": "AlgoArena Prelims",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 12:30 PM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "AlgoArena",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 4:30 PM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "Filmeum",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Media Hall - 413",
      },
      {
        "eventName": "Wave Cloning (R1)",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 10:30 AM",
        "venue": "409",
      },
      {
        "eventName": "Wave Cloning (R1)",
        "eventCategory": "competition",
        "eventTime": "10:30 AM - 4:30 PM",
        "venue": "Communication Lab - 407, Test Lab - 406",
      },
      {
        "eventName": "Vincere Negotium",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 4:30 PM",
        "venue": "511",
      },
      {
        "eventName": "GenAI Workshop",
        "eventCategory": "workshop",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "SDPK - 504",
      },
      {
        "eventName": "Embedded Systems Workshop",
        "eventCategory": "workshop",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "SDPK - 504",
      },
      {
        "eventName": "Go Karting",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "College Ground",
      },
      {
        "eventName": "Tiki Taka",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "College Ground",
      },
      {
        "eventName": "Rhythm Riot",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Elga",
      },
      {
        "eventName": "SplashDown",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "External Auditorium",
      },
      {
        "eventName": "Paintball",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "External Auditorium",
      },
      {
        "eventName": "RoboSoccer",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "Volleybal Court",
      },
      {
        "eventName": "News Desk",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "CCF",
      },
      {
        "eventName": "DJ War",
        "eventCategory": "general",
        "eventTime": "5:30 PM - 7:30 PM",
        "venue": "Amphi",
      },
    ],
  },
  {
    "id": 2,
    "date": "DAY 3",
    "events": [
      {
        "eventName": "Non Tech Guest Lectures",
        "eventCategory": "talk",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "Film Conference",
        "eventCategory": "conference",
        "eventTime": "1:30 PM - 4:00 PM",
        "venue": "Internal Auditorium",
      },
      {
        "eventName": "Game Plan (P)",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 12:30 PM",
        "venue": "315",
      },
      {
        "eventName": "Game Plan Auction",
        "eventCategory": "competition",
        "eventTime": "12:30 PM - 3:30 PM",
        "venue": "315",
      },
      {
        "eventName": "Game Plan (F)",
        "eventCategory": "competition",
        "eventTime": "3:30 PM - 5:30 PM",
        "venue": "315",
      },
      {
        "eventName": "Lumiere (R1)",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 10:30 AM",
        "venue": "301",
      },
      {
        "eventName": "CSI",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "309",
      },
      {
        "eventName": "Reverso",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "311, 312",
      },
      {
        "eventName": "Fun Zone",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "310",
      },
      {
        "eventName": "Blind Coding Prelims",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 12:30 PM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "Blind Coding",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 4:30 PM",
        "venue": "Computer Lab 2 - 303",
      },
      {
        "eventName": "D3",
        "eventCategory": "competition",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "Media Hall - 413",
      },
      {
        "eventName": 'Just "50" (F)',
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "Media Hall - 413",
      },
      {
        "eventName": "MECLabs",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "SDPK - 504",
      },
      {
        "eventName": "Go Karting",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "College Ground",
      },
      {
        "eventName": "Tiki Taka",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "College Ground",
      },
      {
        "eventName": "Paintball",
        "eventCategory": "general",
        "eventTime": "9:30 AM - 5:30 PM",
        "venue": "External Auditorium",
      },
      {
        "eventName": "Fun Zone",
        "eventCategory": "general",
        "eventTime": "11:30 AM - 1:30 PM",
        "venue": "Elga"
      },
      {
        "eventName": "Lumiere(R2)",
        "eventCategory": "competition",
        "eventTime": "11:30 AM - 1:30 PM",
        "venue": "Analog Electronics Lab",
      },
      {
        "eventName": "Lumiere(R3)",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 3:30 PM",
        "venue": "Analog Electronics Lab",
      },
      {
        "eventName": "Pitch Perfect",
        "eventCategory": "workshop",
        "eventTime": "9:30 AM - 1:30 PM",
        "venue": "CCF",
      },
      {
        "eventName": "abraCADabra",
        "eventCategory": "competition",
        "eventTime": "1:30 PM - 5:30 PM",
        "venue": "CCF Hall",
      },
      {
        "eventName": "Musical Gala",
        "eventCategory": "general",
        "eventTime": "5:30 PM - 7:30 PM",
        "venue": "College Ground",
      },
    ],
  },
];
